### ISSUE TITLE
Get this merged into cfe/tools

### ISSUE THREAD

**Issue by kljohann** [kljohann/clang-format.el#2]
See milkypostman/melpa#2202. The major difference to the cfe version seems to be `defcustom`s, displaying return code / stderr-output and package.el-compatibility.

**Comment by Sarcasm** [comment]
Any progress on this? :)

I would like to add special support for Clang format someday in [irony-mode](https://github.com/Sarcasm/irony-mode) and having only one Clang format in the wild may be nice (not sure I will depend on it or not yet).

**Comment by kljohann** [comment]
Hi, I just added some aliases to support calls using the cfe/tools function signature. I will send a patch to the mailing list next week :)

**Comment by Sarcasm** [comment]
Great :)

**Comment by kljohann** [comment]
Okay, I finally got around to doing this :)
http://lists.cs.uiuc.edu/pipermail/cfe-commits/Week-of-Mon-20141229/120600.html

**Comment by Sarcasm** [comment]
If you do not get any response you may want to try by using Phabricator which is what the LLVM folks use for code review, see http://llvm.org/docs/Phabricator.html

The Phabricator URL is http://reviews.llvm.org/

IIRC, you can connect through your Github account, using OAuth.

**Comment by kljohann** [comment]
landed in [r225447](http://lists.cs.uiuc.edu/pipermail/cfe-commits/Week-of-Mon-20150105/120901.html). :)

**Comment by Sarcasm** [comment]
Great!

It is my understand that maybe another change will land that will no longer erase the whole buffer? That would be great! Hopefully that will also play better with `undo` which right now doesn't play very nicely...

Any reason to require json 1.3 instead of 1.2? I think 1.2 is available built-in some Emacs versions (23.1).

**Comment by kljohann** [comment]
Yes, see [this mail to cfe-commits](http://lists.cs.uiuc.edu/pipermail/cfe-commits/Week-of-Mon-20150112/121127.html) or ed4bac9ed0b7 on the xml branch. I now use the `-output-replacements-xml` option of clang-format, which does not yet return the calculated cursor position in 3.5. That said, the position the cursor ends up in isn't too far off in most cases. :)
Btw. I no longer require `json` but `cl-lib 0.3`. Do you know the first version of emacs that included this?

**Comment by Sarcasm** [comment]
Apparently Emacs 24.3 ships with `cl-lib 1.0`. This is the first time it was built-in Emacs.
